#!/bin/bash
adb kill-server
DEVICEIP=`adb shell "ip addr show wlan0 | grep -e wlan0$ | cut -d\" \" -f 6 | cut -d/ -f 1"`

adb tcpip 5555
adb connect $DEVICEIP:5555

if [ $# -eq 1 ]
then
        if [ $1 == 'scrcpy' ]
        then
                scrcpy
        fi
fi
